### ISSUE TITLE
openai.RateLimitError: Error code: 429

### ISSUE THREAD

**Issue by hsbdkdn** [gusye1234/nano-graphrag#104]
I run the using_deepseek_api_as_llm glm_api_as_embedding.py file and explicitly set the relevant API key, but the following error, even after I added rate limiting code later, set it to once every 12s, it still does this. I want to know if the project needs OpenAI's API key for GLM's embedding even when using DeepSeek as the LLM?
ERROR:
INFO:nano-graphrag:Load KV full_docs with 0 data
INFO:nano-graphrag:Load KV text_chunks with 0 data
INFO:nano-graphrag:Load KV llm_response_cache with 2 data
INFO:nano-graphrag:Load KV community_reports with 0 data
INFO:nano-vectordb:Init {'embedding_dim': 1024, 'metric': 'cosine', 'storage_file': './nano_graphrag_cache_deepseek_TEST\\vdb_entities.json'} 0 data
INFO:nano-graphrag:[New Docs] inserting 1 docs
INFO:nano-graphrag:[New Chunks] inserting 1 chunks
INFO:nano-graphrag:[Entity Extraction]...
⠙ Processed 1(100%) chunks,  9 entities(duplicated), 16 relations(duplicated)
INFO:nano-graphrag:Inserting 9 vectors to entities
INFO:httpx:HTTP Request: POST https://open.bigmodel.cn/api/paas/v4/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.453271 seconds
INFO:httpx:HTTP Request: POST https://open.bigmodel.cn/api/paas/v4/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.812722 seconds
INFO:httpx:HTTP Request: POST https://open.bigmodel.cn/api/paas/v4/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:nano-graphrag:Writing graph with 9 nodes, 15 edges
Traceback (most recent call last):
  File "D:\Drivers\pythonProject12\test\try_test.py", line 149, in <module>
    insert()
  File "D:\Drivers\pythonProject12\test\try_test.py", line 142, in insert
    rag.insert(FAKE_TEXT)
  File "D:\conda_base\envs\try\lib\site-packages\nano_graphrag\graphrag.py", line 220, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "D:\conda_base\envs\try\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\conda_base\envs\try\lib\site-packages\nano_graphrag\graphrag.py", line 309, in ainsert
    maybe_new_kg = await self.entity_extraction_func(
  File "D:\conda_base\envs\try\lib\site-packages\nano_graphrag\_op.py", line 421, in extract_entities
    await entity_vdb.upsert(data_for_vdb)
  File "D:\conda_base\envs\try\lib\site-packages\nano_graphrag\_storage\vdb_nanovectordb.py", line 45, in upsert
    embeddings_list = await asyncio.gather(
  File "D:\conda_base\envs\try\lib\site-packages\nano_graphrag\_utils.py", line 251, in wait_func
    result = await func(*args, **kwargs)
  File "D:\Drivers\pythonProject12\test\try_test.py", line 79, in __call__
    return await self.func(*args, **kwargs)
  File "D:\Drivers\pythonProject12\test\try_test.py", line 97, in GLM_embedding
    embedding = client.embeddings.create(
  File "D:\conda_base\envs\try\lib\site-packages\openai\resources\embeddings.py", line 124, in create
    return self._post(
  File "D:\conda_base\envs\try\lib\site-packages\openai\_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "D:\conda_base\envs\try\lib\site-packages\openai\_base_client.py", line 954, in request
    return self._request(
  File "D:\conda_base\envs\try\lib\site-packages\openai\_base_client.py", line 1043, in _request
    return self._retry_request(
  File "D:\conda_base\envs\try\lib\site-packages\openai\_base_client.py", line 1092, in _retry_request
    return self._request(
  File "D:\conda_base\envs\try\lib\site-packages\openai\_base_client.py", line 1043, in _request
    return self._retry_request(
  File "D:\conda_base\envs\try\lib\site-packages\openai\_base_client.py", line 1092, in _retry_request
    return self._request(
  File "D:\conda_base\envs\try\lib\site-packages\openai\_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'code': '1113', 'message': '您的账户已欠费，请充值后重试。'}}

speed_limted_code:
last_request_time=0
REQUEST_INTERVAL=60/5
async def deepseek_model_if_cache_limited(
        prompt,system_prompt=None,history_messages=[],**kwargs
)->str:
    global last_request_time
    current_time=time.time()
    if current_time-last_request_time<REQUEST_INTERVAL:
        await asyncio.sleep(REQUEST_INTERVAL-(current_time-last_request_time))
    last_request_time=time.time()
    return await deepseepk_model_if_cache(prompt,system_prompt,history_messages,**kwargs)

**Comment by codeScourge** [comment]
Try lowering "best_model_max_async" and "cheap_model_max_async". Depends on your account, but for me (tier 2) going from 16 to 4 fixed it.
