### ISSUE TITLE
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 502 Bad Gateway"

### ISSUE THREAD

**Issue by xxxibgdrgn123** [gusye1234/nano-graphrag#29]
Hello, I have encountered a problem that I have been unable to solve. I am using the local deployment method of ollama, and ollama is enabled normally. However, after running the using_ollama_as_llm.py file, the following error message keeps appearing, and there is no relevant access record in the logs of ollama serve. However, I used curl to POST access it http://127.0.0.1:11434/api/chat It's normal and there are access records. May I ask what the reason is?

`INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 502 Bad Gateway"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 502 Bad Gateway"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 502 Bad Gateway"
INFO:nano-graphrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "D:\download\nano-graphrag-main\examples\using_ollama_as_llm.py", line 91, in <module>
    insert()
  File "D:\download\nano-graphrag-main\examples\using_ollama_as_llm.py", line 84, in insert
    rag.insert(FAKE_TEXT)
  File "d:\download\nano-graphrag-main\nano_graphrag\graphrag.py", line 169, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "D:\conda\envs\nano-GraphRAG\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\download\nano-graphrag-main\nano_graphrag\graphrag.py", line 251, in ainsert
    maybe_new_kg = await extract_entities(
  File "d:\download\nano-graphrag-main\nano_graphrag\_op.py", line 314, in extract_entities
    results = await asyncio.gather(
  File "d:\download\nano-graphrag-main\nano_graphrag\_op.py", line 253, in _process_single_content
    final_result = await use_llm_func(hint_prompt)
  File "d:\download\nano-graphrag-main\nano_graphrag\_utils.py", line 165, in wait_func
    result = await func(*args, **kwargs)
  File "D:\download\nano-graphrag-main\examples\using_ollama_as_llm.py", line 34, in ollama_model_if_cache
    response = await ollama_client.chat(model=MODEL, messages=messages, **kwargs)
  File "D:\conda\envs\nano-GraphRAG\lib\site-packages\ollama\_client.py", line 654, in chat
    return await self._request_stream(
  File "D:\conda\envs\nano-GraphRAG\lib\site-packages\ollama\_client.py", line 518, in _request_stream
    response = await self._request(*args, **kwargs)
  File "D:\conda\envs\nano-GraphRAG\lib\site-packages\ollama\_client.py", line 488, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError`

**Comment by gusye1234** [comment]
Hi, it seems like a connection error to your ollama, not a bug in `nano-graphrag`
