### ISSUE TITLE
ModuleNotFoundError: No module named 'milvus_lite'报错

### ISSUE THREAD

**Issue by zhaofangtao** [gusye1234/nano-graphrag#5]
![1723878341136](https://github.com/user-attachments/assets/8ac323d9-8f49-495d-ab1f-c7ceb2c056e3)

Traceback (most recent call last):
  File "F:\github\nano-graphrag\venv\Lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 651, in _create_connection
    raise ex from ex
  File "F:\github\nano-graphrag\venv\Lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 648, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "F:\github\nano-graphrag\venv\Lib\site-packages\pymilvus\orm\connections.py", line 378, in connect
    from milvus_lite.server_manager import server_manager_instance
ModuleNotFoundError: No module named 'milvus_lite'

请问老师，MilvusLiteStorge如何替换成自定义的向量库呢。我查了Milvus lite官方issue，回应目前 milvus-lite 还不支持原生 Windows 安装。导致无法使用Milvus

**Comment by gusye1234** [comment]
好的 你希望支持什么向量数据库呢？Chroma？可以去Issue #2 下投票～ 下个版本会考虑添加
或者你可以参考`MilvusLiteStorage`的实现， 只要继承自`BaseVectorStorage`并且实现了对应的几个接口就可以直接替换`vector_db_storage_cls`这个参数
