### ISSUE TITLE
关于google的gemini-1.5-flash模型的调用

### ISSUE THREAD

**Issue by luckfu** [gusye1234/nano-graphrag#54]
我用gemini-1.5-flash 生成图谱数据可以，但是执行query报错
```python

API_KEY = "key value"
MODEL = "gemini-1.5-flash"


#EMBEDDING_MODEL="models/text-embedding-004"
#EMBEDDING_DIM=768
#EMBEDDING_TOKENS=2048

EMBEDDING_URL="http://localhost:11434/v1"
EMBEDDING_MODEL="bge-m3"
EMBEDDING_DIM=1024
EMBEDDING_TOKENS=8192

llm_model_max_async=1
embedding_max_async=1
BATCH_SIZE = 1  # 每个批次的大小

Timeout=90.0

# 初始化计数器
total_calls = 0
calls_per_minute = 0
last_reset_time = time.time()

WORKING_DIR = "./db/"

async def google_model_if_cache(
    prompt: str, 
    system_prompt: str = None, 
    history_messages: List[Dict[str, str]] = [], 
    **kwargs
) -> str:
    global total_calls, calls_per_minute, last_reset_time

    # 检查是否需要重置每分钟计数器
    current_time = time.time()
    if current_time - last_reset_time >= 60:  # 每分钟重置一次
        calls_per_minute = 0
        last_reset_time = current_time

    # 如果每分钟调用次数达到 15 次，等待到下一分钟
    if calls_per_minute >= 15:
        wait_time = 60 - (current_time - last_reset_time)
        if wait_time > 0:
            print(f"每分钟调用次数达到 15 次，等待 {wait_time:.2f} 秒...")
            time.sleep(wait_time)
        calls_per_minute = 0
        last_reset_time = time.time()

    # 创建生成模型实例
    model = genai.GenerativeModel(MODEL)
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})

    # 获取缓存的响应（如果有）
    hashing_kv: BaseKVStorage = kwargs.pop("hashing_kv", None)
    messages.extend(history_messages)
    messages.append({"role": "user", "content": prompt})
    if hashing_kv is not None:
        args_hash = compute_args_hash(MODEL, messages)
        if_cache_return = await hashing_kv.get_by_id(args_hash)
        if if_cache_return is not None:
            return if_cache_return["return"]

    max_retries = 3  # 最大重试次数
    retry_delay = 5  # 初始重试延迟（秒）

    for attempt in range(max_retries):
        try:
            # 生成内容
            response = model.generate_content(prompt)
            # 只有在实际生成内容时才进行计数
            total_calls += 1
            calls_per_minute += 1
            break  # 成功生成内容，退出重试循环
        except requests.exceptions.HTTPError as e:
            print(f"总调用次数: {total_calls}, 每分钟调用次数: {calls_per_minute}")
            # 检查是否是 HTTP 429 错误
            if e.response.status_code == 429:
                print("请求内容:", messages)
                print("错误信息: 速率限制错误 (HTTP 429)")
                if attempt < max_retries - 1:
                    print(f"重试次数: {attempt + 1}, 等待 {retry_delay} 秒后重试...")
                    time.sleep(retry_delay)
                    retry_delay *= 2  # 指数退避策略
                else:
                    raise  # 达到最大重试次数，重新抛出异常
            else:
                raise  # 其他 HTTP 错误，重新抛出异常
        except Exception as e:
            # 打印出导致错误的消息
            print("请求内容:", messages)
            print("错误信息:", str(e))
            raise  # 重新抛出异常

    # 缓存响应（如果有）
    if hashing_kv is not None:
        await hashing_kv.upsert(
            {args_hash: {"return": response.text, "model": MODEL}}
        )
    return response.text

@wrap_embedding_func_with_attrs(embedding_dim=EMBEDDING_DIM, max_token_size=EMBEDDING_TOKENS)
async def custom_embedding(texts: list[str]) -> np.ndarray:
    url = f"{EMBEDDING_URL}/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}"
    }

    all_embeddings = []

    async with aiohttp.ClientSession() as session:
        for i in tqdm(range(0, len(texts), BATCH_SIZE), desc="Processing embeddings "):
            batch_texts = texts[i:i + BATCH_SIZE]
            payload = {
                "model": EMBEDDING_MODEL,
                "input": batch_texts
            }

            async with session.post(url, json=payload, headers=headers) as response:
                if response.status != 200:
                    print(payload)
                    raise Exception(f"Failed to get embeddings: {response.status}")
                data = await response.json()
                embeddings = [np.array(dp["embedding"]) for dp in data["data"]]
                all_embeddings.extend(embeddings)

    return np.array(all_embeddings)

def query():
    rag = GraphRAG(
        working_dir=WORKING_DIR,
        enable_llm_cache=True,
        embedding_func=custom_embedding,
        best_model_func=google_model_if_cache,
        cheap_model_func=google_model_if_cache,
        convert_response_to_json_func=check_json,
        best_model_max_token_size=8192,
        best_model_max_async=1,
        cheap_model_max_token_size=8192,
        cheap_model_max_async=1,
        enable_naive_rag=True,
        embedding_func_max_async=embedding_max_async,
    )
    print(
        rag.query(
            "太乙金华宗旨怎么修炼?", param=QueryParam(mode="global")
        )
    )

if __name__ == "__main__":
    #insert()
    query()
```
执行结果：
```bash
(base) $ python nanoRag_gemini.py 
DEBUG:nano-graphrag:GraphRAG init with param:

  working_dir = ./db/,
  enable_local = True,
  enable_naive_rag = True,
  chunk_func = <function chunking_by_token_size at 0xfffde3e0e440>,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  graph_cluster_algorithm = leiden,
  max_graph_cluster_size = 10,
  graph_cluster_seed = 3735928559,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  special_community_report_llm_kwargs = {'response_format': {'type': 'json_object'}},
  embedding_func = {'embedding_dim': 1024, 'max_token_size': 8192, 'func': <function custom_embedding at 0xfffddfbaea70>},
  embedding_batch_num = 32,
  embedding_func_max_async = 1,
  query_better_than_threshold = 0.2,
  using_azure_openai = False,
  best_model_func = <function google_model_if_cache at 0xfffddfbae8c0>,
  best_model_max_token_size = 8192,
  best_model_max_async = 1,
  cheap_model_func = <function google_model_if_cache at 0xfffddfbae8c0>,
  cheap_model_max_token_size = 8192,
  cheap_model_max_async = 1,
  entity_extraction_func = <function extract_entities at 0xfffde3e0e680>,
  key_string_value_json_storage_cls = <class 'nano_graphrag._storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'nano_graphrag._storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'nano_graphrag._storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function check_json at 0xfffddfbae200>

INFO:nano-graphrag:Load KV full_docs with 103 data
INFO:nano-graphrag:Load KV text_chunks with 154 data
INFO:nano-graphrag:Load KV llm_response_cache with 1841 data
INFO:nano-graphrag:Load KV community_reports with 127 data
INFO:nano-graphrag:Loaded graph from ./db/graph_chunk_entity_relation.graphml with 701 nodes, 840 edges
INFO:nano-vectordb:Load (673, 1024) data
INFO:nano-vectordb:Init {'embedding_dim': 1024, 'metric': 'cosine', 'storage_file': './db/vdb_entities.json'} 673 data
INFO:nano-vectordb:Load (154, 1024) data
INFO:nano-vectordb:Init {'embedding_dim': 1024, 'metric': 'cosine', 'storage_file': './db/vdb_chunks.json'} 154 data
INFO:nano-graphrag:Revtrieved 121 communities
INFO:nano-graphrag:Grouping to 5 groups for global search
Traceback (most recent call last):
  File "/data/notebook/llm/graphGrap/nanoRag_gemini.py", line 278, in <module>
    query()
  File "/data/notebook/llm/graphGrap/nanoRag_gemini.py", line 271, in query
    rag.query(
  File "/data/notebook/llm/graphGrap/./nano-graphrag/nano_graphrag/graphrag.py", line 221, in query
    return loop.run_until_complete(self.aquery(query, param))
  File "/data/miniconda3/lib/python3.10/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/data/miniconda3/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/data/miniconda3/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/data/notebook/llm/graphGrap/./nano-graphrag/nano_graphrag/graphrag.py", line 239, in aquery
    response = await global_query(
  File "/data/notebook/llm/graphGrap/./nano-graphrag/nano_graphrag/_op.py", line 1028, in global_query
    map_communities_points = await _map_global_communities(
  File "/data/notebook/llm/graphGrap/./nano-graphrag/nano_graphrag/_op.py", line 983, in _map_global_communities
    responses = await asyncio.gather(*[_process(c) for c in community_groups])
  File "/data/miniconda3/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/data/miniconda3/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/data/notebook/llm/graphGrap/./nano-graphrag/nano_graphrag/_op.py", line 980, in _process
    return data.get("points", [])
AttributeError: 'str' object has no attribute 'get'
```
在gemini-1.5-flash生成图谱数据后，改用deepseek接口去query是没有问题的

**Comment by luckfu** [comment]
我的错，这里有个低级错误，但是也发现用gemini 的api的确和like openai的接口区别有点大，算了，用了个转发项目的代码

**Comment by austinmyc** [comment]
@luckfu 最後用了什麼方式解決呢?
